<?
$aMenuLinks = Array(
	Array(
		"Realty", 
		"/realty/list/", 
		Array(), 
		Array("icon"=>"home.png"), 
		"" 
	),
	Array(
		"Archive", 
		"/realty/archive/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Removed", 
		"/realty/removed/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1))"
	),	
	Array(
		"Clients requests", 
		"/realty/client-requests/", 
		Array(), 
		Array("icon"=>"list.png"), 
		"" 
	),	
	Array(
		"Removed requests", 
		"/realty/client-requests/removed/", 
		Array(), 
		Array("icon"=>"list.png"), 
		"CSite::InGroup(array(1))" 
	),	
	Array(
		"Visits history", 
		"/realty/visits/", 
		Array(), 
		Array("icon"=>"people.png"), 
		"" 
	),
	Array(
		"Contacts", 
		"/realty/clients/", 
		Array(), 
		Array("icon"=>"people.png"), 
		"" 
	),		
	Array(
		"Blocked", 
		"/realty/blocked/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(1,13))" 
	),	
);
?>